In [9]:
# Question 1(a)
import numpy as np

# Creating 3x3 array
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Matrix:\n", a)
print("Transpose:\n", a.T)

determinant = np.linalg.det(a)
print("Determinant:", determinant)

if np.isclose(determinant, 0):
    print("Matrix is singular → Inverse does not exist.")
else:
    inverse = np.linalg.inv(a)
    print("Inverse:\n", inverse)

eigvals= np.linalg.eig(a)
print("Eigenvalues:\n", eigvals)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinant: 0.0
Matrix is singular → Inverse does not exist.
Eigenvalues:
 EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [10]:
#Question no 1(b)
import numpy as np

# Create matrices
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])   # 3x4 matrix

Y = np.array([[2, 0],
              [1, 2],
              [0, 1],
              [1, 0]])            # 4x2 matrix

print("Matrix X:\n", X)
print("Matrix Y:\n", Y)


Z = np.dot(X, Y)  
print("Result of X * Y:\n", Z)


Matrix X:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matrix Y:
 [[2 0]
 [1 2]
 [0 1]
 [1 0]]
Result of X * Y:
 [[ 8  7]
 [24 19]
 [40 31]]


In [12]:
# Question 1(c)
import numpy as np

#(A)
A = np.array([[2, 1, -1],
              [-3,-1, 2],
              [-2, 1, 2]])

#(B)
B = np.array([8,-11,-3])

print("Coefficient Matrix A:\n", A)
print("Constants B:\n", B)

X = np.linalg.solve(A, B)
print("Solution (x, y, z):", X)


Coefficient Matrix A:
 [[ 2  1 -1]
 [-3 -1  2]
 [-2  1  2]]
Constants B:
 [  8 -11  -3]
Solution (x, y, z): [ 2.  3. -1.]


In [23]:
#Question no 2(a)
import numpy as np

A = np.random.randint(1, 101, size=(10, 10))
print("Original 10x10 Matrix:\n", A)

diagonal = np.diag(A)
mean = np.mean(diagonal)
print("\nMain Diagonal:", diagonal)
print("Mean of Diagonal:", mean)

row_sums = np.sum(A, axis=1)
A[:, -1] = row_sums
print("\nModified Matrix (last column replaced with row sums):\n", A)


Original 10x10 Matrix:
 [[ 72  68  21  58  99  85  14  20  41  74]
 [ 29   9   5   6  60   9  38  33  53  19]
 [ 99  33  29  79  91   8  63  69  60  86]
 [ 61  72  19 100   8  51  44  84  35  78]
 [ 90  13  54  67  38  35  15  77  15  86]
 [ 77  49  71   9  25  90  89  86  19  97]
 [100   8  26  16  87  38  10  84  82  79]
 [ 92   7  93  28  29  58   1  69  19  13]
 [ 85  31  61  64  46  97  10  68  59  81]
 [ 36   4  50  63  57   7  52  82  34  85]]

Main Diagonal: [ 72   9  29 100  38  90  10  69  59  85]
Mean of Diagonal: 56.1

Modified Matrix (last column replaced with row sums):
 [[ 72  68  21  58  99  85  14  20  41 552]
 [ 29   9   5   6  60   9  38  33  53 261]
 [ 99  33  29  79  91   8  63  69  60 617]
 [ 61  72  19 100   8  51  44  84  35 552]
 [ 90  13  54  67  38  35  15  77  15 490]
 [ 77  49  71   9  25  90  89  86  19 612]
 [100   8  26  16  87  38  10  84  82 530]
 [ 92   7  93  28  29  58   1  69  19 409]
 [ 85  31  61  64  46  97  10  68  59 602]
 [ 36   4  50  63  57

In [19]:
#Question no 2(b)
import numpy as np
n = 5

i = np.arange(n).reshape(n, 1)   # column vector
j = np.arange(n).reshape(1, n)   # row vector

A = i**2 + j**2
print("5x5 Matrix:\n", A)



5x5 Matrix:
 [[ 0  1  4  9 16]
 [ 1  2  5 10 17]
 [ 4  5  8 13 20]
 [ 9 10 13 18 25]
 [16 17 20 25 32]]


In [31]:
#Question no 2(c)
import numpy as np

A = np.random.randint(1, 101, size=20)
print("Original Array:\n", A)

mean = np.mean(A)
A[A > mean] = -1
print("Modified Array:\n", A)

indices = np.argsort(A)[-5:][::-1]
print("Indices of Top 5 Elements:\n", indices)


Original Array:
 [65 25 73  2 22 23 83 33 57 32 91 85 91 76 10 38  3 39 23 69]
Modified Array:
 [-1 25 -1  2 22 23 -1 33 -1 32 -1 -1 -1 -1 10 38  3 39 23 -1]
Indices of Top 5 Elements:
 [17 15  7  9  1]


In [55]:
# Question no 3 
import numpy as np

np.random.seed(0)
days = np.arange(1, 101)
slope = 0.2
intercept = 50.0
noise = np.random.normal(0, 1.5, size=100)
prices = intercept + slope * days + noise

X_mean = np.mean(days)
y_mean = np.mean(prices)
m = np.sum((days - X_mean) * (prices - y_mean)) / np.sum((days - X_mean) ** 2)
c = y_mean - m * X_mean

y_pred = m * days + c
mse = np.mean((prices - y_pred) ** 2) / len(days)

y_101 = m * 101 + c

if y_101 > prices[99]:
    decision = "BUY"
else:
    decision = "CASH"

if decision == "BUY":
    final_value = 100 * y_101
else:
    final_value = 1000

print("Predicted Next Day Price:", y_101)
print("Last Actual Price:", prices[99])
print("Decision (Buy or Cash):", decision)
print("Final Value:", final_value)

Predicted Next Day Price: 70.06221192234597
Last Actual Price: 70.60298404516705
Decision (Buy or Cash): CASH
Final Value: 1000
